In [24]:
#import
import numpy as np

#maxpool with padding
def conv_2d(input_matrix, kernel, stride, padding):
  #init
  out_row = int(((input_matrix.shape[0] - kernel.shape[0] + 2 * padding[0]) / stride[0]) + 1)
  out_col = int(((input_matrix.shape[1] - kernel.shape[1] + 2 * padding[1]) / stride[1]) + 1)
  input_matrix = np.pad(input_matrix, ((padding[0], padding[1]), (padding[0], padding[1])))
  outputs = np.zeros((out_row, out_col))
  #iterate
  for i in range(outputs.shape[0]):
    i_init = i * stride[0]
    i_delta = i_init + kernel.shape[0]
    #iterate
    for j in range(outputs.shape[1]):
      j_init = j * stride[1]
      j_delta = j_init + kernel.shape[1]
      #maxpool
      small_matrix = input_matrix[i_init:i_delta, j_init:j_delta]
      outputs[i, j] = np.sum(small_matrix * kernel)
  #return
  return outputs

#main
input_matrix = np.random.randint(1, 10, (7, 7))
kernel = np.random.randint(1, 10, (3, 3))
stride = (2, 2)
padding = (1, 1)

#maxpool
conv_outputs = conv_2d(input_matrix, kernel, stride, padding)

#print
print(conv_outputs)

[[ 84. 180. 260. 158.]
 [ 80. 234. 191. 131.]
 [ 82. 191. 215. 112.]
 [ 72. 149. 124.  37.]]


In [25]:
#import
import torch
#init
input_tensor = torch.Tensor(np.expand_dims(input_matrix, axis = (0, 1)))
#init
input_kernel = torch.Tensor(np.expand_dims(kernel, axis = (0, 1)))
#main
conv_2d_torch = torch.nn.functional.conv2d(input_tensor, input_kernel, stride = stride, padding = padding)
#print
print(conv_2d_torch)

tensor([[[[ 84., 180., 260., 158.],
          [ 80., 234., 191., 131.],
          [ 82., 191., 215., 112.],
          [ 72., 149., 124.,  37.]]]])
