In [38]:
#import
import numpy as np

#maxpool with padding
def maxpool_2d(input_matrix, kernel_size, stride, padding):
  #init
  out_row = int(((input_matrix.shape[0] - kernel_size[0] + 2 * padding[0]) / stride[0]) + 1)
  out_col = int(((input_matrix.shape[1] - kernel_size[1] + 2 * padding[1]) / stride[1]) + 1)
  input_matrix = np.pad(input_matrix, ((padding[0], padding[1]), (padding[0], padding[1])))
  outputs = np.zeros((out_row, out_col))
  #iterate
  for i in range(outputs.shape[0]):
    i_init = i * stride[0]
    i_delta = i_init + kernel_size[0]
    #iterate
    for j in range(outputs.shape[1]):
      j_init = j * stride[1]
      j_delta = j_init + kernel_size[1]
      #maxpool
      small_matrix = input_matrix[i_init:i_delta, j_init:j_delta]
      outputs[i, j] = small_matrix.max()
  #return
  return outputs

#main
input_matrix = np.random.randint(1, 10, (5, 5))
kernel_size = (3, 2)
stride = (2, 1)
padding = (1, 1)

#maxpool
maxpool = maxpool_2d(input_matrix, kernel_size, stride, padding)

#print
print(maxpool)

[[9. 9. 7. 9. 9. 9.]
 [9. 9. 8. 9. 9. 8.]
 [5. 8. 8. 8. 4. 4.]]


In [39]:
#import
import torch

#main
pooler = torch.nn.MaxPool2d(kernel_size, stride, padding=padding)
#init
input_tensor = torch.Tensor(np.expand_dims(input_matrix, axis = (0, 1)))
#apply
torch_maxpool = pooler(input_tensor)
#print
print(torch_maxpool)

tensor([[[[9., 9., 7., 9., 9., 9.],
          [9., 9., 8., 9., 9., 8.],
          [5., 8., 8., 8., 4., 4.]]]])
